import{auth,db,ADMIN_UID}from"./firebase.js";import{onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";import{collection,getDocs,addDoc,updateDoc,deleteDoc,doc,getDoc,setDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const $=s=>document.querySelector(s),esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));let type,id,data={};
onAuthStateChanged(auth,u=>{if(!u||u.uid!==ADMIN_UID){location.replace("login.html");return}$("#guard").hidden=true;$("#dash").hidden=false;refresh()});
$("#logout").onclick=()=>signOut(auth).then(()=>location.replace("login.html"));
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>document.querySelectorAll(".panel").forEach(p=>p.hidden=p.id!==b.dataset.tab));
async function all(t){let s=await getDocs(collection(db,t));return s.docs.map(d=>({id:d.id,...d.data()}))}
async function refresh(){await render("projects","#projectsList");await render("certificates","#certList");await render("skills","#skillList");await profile()}
async function render(t,sel){let a=await all(t);$(sel).innerHTML=a.map(x=>`<div class="row"><div><b>${esc(x.title||x.name)}</b><small>${esc(x.provider||x.category||x.description)}</small></div><div class="actions"><button data-e="${x.id}" data-t="${t}">Edit</button><button class="danger" data-d="${x.id}" data-t="${t}">Delete</button></div></div>`).join("")||"<p>No items yet.</p>";document.querySelectorAll("[data-e]").forEach(b=>b.onclick=()=>edit(b.dataset.t,b.dataset.e));document.querySelectorAll("[data-d]").forEach(b=>b.onclick=async()=>{if(confirm("Delete?")){await deleteDoc(doc(db,b.dataset.t,b.dataset.d));refresh()}})}
function fields(t,d={}){if(t==="projects")return`<label>Title<input name="title" value="${esc(d.title)}" required></label><label>Category<input name="category" value="${esc(d.category)}"></label><label>Description<textarea name="description">${esc(d.description)}</textarea></label><label>Image URL<input name="image" value="${esc(d.image)}"></label><label>Tools<input name="tools" value="${esc((d.tools||[]).join(", "))}"></label><button>Save</button>`;if(t==="certificates")return`<label>Title<input name="title" value="${esc(d.title)}" required></label><label>Provider<input name="provider" value="${esc(d.provider)}"></label><label>Description<textarea name="description">${esc(d.description)}</textarea></label><label>Image URL<input name="image" value="${esc(d.image)}"></label><button>Save</button>`;return`<label>Name<input name="name" value="${esc(d.name)}" required></label><label>Description<textarea name="description">${esc(d.description)}</textarea></label><button>Save</button>`}
async function edit(t,i=null){type=t;id=i;data=i?(await getDoc(doc(db,t,i))).data()||{}:{};$("#mt").textContent=(i?"Edit ":"Add ")+t;$("#editor").innerHTML=fields(t,data);$("#modal").hidden=false;$("#editor").onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));if(t==="projects")o.tools=o.tools.split(",").map(x=>x.trim()).filter(Boolean);if(i)await updateDoc(doc(db,t,i),o);else{o.createdAt=serverTimestamp();await addDoc(collection(db,t),o)}$("#modal").hidden=true;refresh()}}
$("#close").onclick=()=>$("#modal").hidden=true;$("#addProject").onclick=()=>edit("projects");$("#addCert").onclick=()=>edit("certificates");$("#addSkill").onclick=()=>edit("skills");
async function profile(){let s=await getDoc(doc(db,"profile","main")),p=s.exists()?s.data():{};$("#profileForm").innerHTML=["name","title","university","graduation","location","email","linkedin","bio"].map(k=>`<label>${k}<input name="${k}" value="${esc(p[k])}"></label>`).join("")+"<button>Save Profile</button>";$("#profileForm").onsubmit=async e=>{e.preventDefault();await setDoc(doc(db,"profile","main"),Object.fromEntries(new FormData(e.target)),{merge:true})}}
